apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapi
  labels:
    app: demo-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-webapi
  template:
    metadata:
      labels:
        app: demo-webapi
    spec:
      containers:
      - name: demo-webapi
        image: cgillum/durabletask-samples-webapi:latest
        ports:
        - containerPort: 8080
      - name: durabletask-sidecar
        image: cgillum/durabletask-sidecar:latest
        ports:
        - containerPort: 4001
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: c1b602ab-2591-4791-8729-c803e9f5d518
        args: ["start", "--backend", "Emulator"]
---
apiVersion: v1
kind: Service
metadata:
  name: demo-webapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: demo-webapi